[2025-09-20T12:06:53.409+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: manual_full_load.load_fct_promotions manual__2025-09-20T10:06:48.685593+00:00 [queued]>
[2025-09-20T12:06:53.418+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: manual_full_load.load_fct_promotions manual__2025-09-20T10:06:48.685593+00:00 [queued]>
[2025-09-20T12:06:53.418+0200] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-09-20T12:06:53.428+0200] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): load_fct_promotions> on 2025-09-20 10:06:48.685593+00:00
[2025-09-20T12:06:53.431+0200] {standard_task_runner.py:57} INFO - Started process 7620 to run task
[2025-09-20T12:06:53.433+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'manual_full_load', 'load_fct_promotions', 'manual__2025-09-20T10:06:48.685593+00:00', '--job-id', '123', '--raw', '--subdir', 'DAGS_FOLDER/manual_full_load.py', '--cfg-path', '/tmp/tmp2avyjgn2']
[2025-09-20T12:06:53.435+0200] {standard_task_runner.py:85} INFO - Job 123: Subtask load_fct_promotions
[2025-09-20T12:06:53.484+0200] {task_command.py:410} INFO - Running <TaskInstance: manual_full_load.load_fct_promotions manual__2025-09-20T10:06:48.685593+00:00 [running]> on host 1102361e702e
[2025-09-20T12:06:53.573+0200] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='manual_full_load' AIRFLOW_CTX_TASK_ID='load_fct_promotions' AIRFLOW_CTX_EXECUTION_DATE='2025-09-20T10:06:48.685593+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-20T10:06:48.685593+00:00'
[2025-09-20T12:06:53.577+0200] {sql.py:265} INFO - Executing: 
        INSERT INTO dwh.fct_promotions (promo_id, product_id, start_date, end_date, discount, description)
        SELECT promo_id, product_id, start_date, end_date, discount, description
        FROM staging.promotions_stg;
        
[2025-09-20T12:06:53.601+0200] {base.py:73} INFO - Using connection ID 'postgres_retail' for task execution.
[2025-09-20T12:06:53.664+0200] {base.py:73} INFO - Using connection ID 'postgres_retail' for task execution.
[2025-09-20T12:06:53.669+0200] {sql.py:375} INFO - Running statement: 
        INSERT INTO dwh.fct_promotions (promo_id, product_id, start_date, end_date, discount, description)
        SELECT promo_id, product_id, start_date, end_date, discount, description
        FROM staging.promotions_stg;
        , parameters: None
[2025-09-20T12:06:53.672+0200] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "fct_promotions_pkey"
DETAIL:  Key (promo_id)=(1) already exists.

[2025-09-20T12:06:53.691+0200] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=manual_full_load, task_id=load_fct_promotions, execution_date=20250920T100648, start_date=20250920T100653, end_date=20250920T100653
[2025-09-20T12:06:53.713+0200] {standard_task_runner.py:109} ERROR - Failed to execute job 123 for task load_fct_promotions (duplicate key value violates unique constraint "fct_promotions_pkey"
DETAIL:  Key (promo_id)=(1) already exists.
; 7620)
[2025-09-20T12:06:53.736+0200] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-09-20T12:06:53.779+0200] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
