[2025-09-20T11:23:07.400+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: raw_to_staging.load_competitors_stg scheduled__2025-09-19T00:00:00+00:00 [queued]>
[2025-09-20T11:23:07.416+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: raw_to_staging.load_competitors_stg scheduled__2025-09-19T00:00:00+00:00 [queued]>
[2025-09-20T11:23:07.417+0200] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-09-20T11:23:07.438+0200] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): load_competitors_stg> on 2025-09-19 00:00:00+00:00
[2025-09-20T11:23:07.444+0200] {standard_task_runner.py:57} INFO - Started process 3648 to run task
[2025-09-20T11:23:07.461+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'raw_to_staging', 'load_competitors_stg', 'scheduled__2025-09-19T00:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/dag_raw_to_staging.py', '--cfg-path', '/tmp/tmpfjbcoxqr']
[2025-09-20T11:23:07.471+0200] {standard_task_runner.py:85} INFO - Job 22: Subtask load_competitors_stg
[2025-09-20T11:23:07.610+0200] {task_command.py:410} INFO - Running <TaskInstance: raw_to_staging.load_competitors_stg scheduled__2025-09-19T00:00:00+00:00 [running]> on host 1102361e702e
[2025-09-20T11:23:07.803+0200] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='raw_to_staging' AIRFLOW_CTX_TASK_ID='load_competitors_stg' AIRFLOW_CTX_EXECUTION_DATE='2025-09-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-19T00:00:00+00:00'
[2025-09-20T11:23:07.805+0200] {sql.py:265} INFO - Executing: 
            INSERT INTO staging.competitors_stg (check_date, competitor, product_id, price)
            SELECT date::date, competitor, product_id, price
            FROM raw.competitors_api;
        
[2025-09-20T11:23:07.898+0200] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-09-20T11:23:08.033+0200] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-09-20T11:23:08.045+0200] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 342, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 145, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "postgres" (172.18.0.2), port 5432 failed: FATAL:  password authentication failed for user "postgres"

[2025-09-20T11:23:08.065+0200] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=raw_to_staging, task_id=load_competitors_stg, execution_date=20250919T000000, start_date=20250920T092307, end_date=20250920T092308
[2025-09-20T11:23:08.084+0200] {standard_task_runner.py:109} ERROR - Failed to execute job 22 for task load_competitors_stg (connection to server at "postgres" (172.18.0.2), port 5432 failed: FATAL:  password authentication failed for user "postgres"
; 3648)
[2025-09-20T11:23:08.101+0200] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-09-20T11:23:08.157+0200] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
