[2025-09-20T11:52:44.562+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: manual_full_load.load_sales_staging manual__2025-09-20T09:52:40.324658+00:00 [queued]>
[2025-09-20T11:52:44.570+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: manual_full_load.load_sales_staging manual__2025-09-20T09:52:40.324658+00:00 [queued]>
[2025-09-20T11:52:44.571+0200] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-09-20T11:52:44.587+0200] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): load_sales_staging> on 2025-09-20 09:52:40.324658+00:00
[2025-09-20T11:52:44.591+0200] {standard_task_runner.py:57} INFO - Started process 6230 to run task
[2025-09-20T11:52:44.596+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'manual_full_load', 'load_sales_staging', 'manual__2025-09-20T09:52:40.324658+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/manual_full_load.py', '--cfg-path', '/tmp/tmp1ta8v4fs']
[2025-09-20T11:52:44.599+0200] {standard_task_runner.py:85} INFO - Job 48: Subtask load_sales_staging
[2025-09-20T11:52:44.664+0200] {task_command.py:410} INFO - Running <TaskInstance: manual_full_load.load_sales_staging manual__2025-09-20T09:52:40.324658+00:00 [running]> on host 1102361e702e
[2025-09-20T11:52:44.758+0200] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='manual_full_load' AIRFLOW_CTX_TASK_ID='load_sales_staging' AIRFLOW_CTX_EXECUTION_DATE='2025-09-20T09:52:40.324658+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-20T09:52:40.324658+00:00'
[2025-09-20T11:52:44.759+0200] {sql.py:265} INFO - Executing: 
        INSERT INTO staging.sales_stg (sale_id, product_id, store_id, sale_date, qty, revenue)
        SELECT sale_id, product_id, store_id, sale_date, qty, revenue
        FROM raw.sales;
        
[2025-09-20T11:52:44.781+0200] {base.py:73} INFO - Using connection ID 'postgres_retail' for task execution.
[2025-09-20T11:52:44.849+0200] {base.py:73} INFO - Using connection ID 'postgres_retail' for task execution.
[2025-09-20T11:52:44.856+0200] {sql.py:375} INFO - Running statement: 
        INSERT INTO staging.sales_stg (sale_id, product_id, store_id, sale_date, qty, revenue)
        SELECT sale_id, product_id, store_id, sale_date, qty, revenue
        FROM raw.sales;
        , parameters: None
[2025-09-20T11:52:44.858+0200] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "sale_id" of relation "sales_stg" does not exist
LINE 2:         INSERT INTO staging.sales_stg (sale_id, product_id, ...
                                               ^

[2025-09-20T11:52:44.872+0200] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=manual_full_load, task_id=load_sales_staging, execution_date=20250920T095240, start_date=20250920T095244, end_date=20250920T095244
[2025-09-20T11:52:44.884+0200] {standard_task_runner.py:109} ERROR - Failed to execute job 48 for task load_sales_staging (column "sale_id" of relation "sales_stg" does not exist
LINE 2:         INSERT INTO staging.sales_stg (sale_id, product_id, ...
                                               ^
; 6230)
[2025-09-20T11:52:44.897+0200] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-09-20T11:52:44.982+0200] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
