[2025-09-20T11:58:31.010+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: manual_full_load.load_dim_store manual__2025-09-20T09:48:23.778100+00:00 [queued]>
[2025-09-20T11:58:31.020+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: manual_full_load.load_dim_store manual__2025-09-20T09:48:23.778100+00:00 [queued]>
[2025-09-20T11:58:31.022+0200] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-09-20T11:58:31.034+0200] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): load_dim_store> on 2025-09-20 09:48:23.778100+00:00
[2025-09-20T11:58:31.038+0200] {standard_task_runner.py:57} INFO - Started process 6774 to run task
[2025-09-20T11:58:31.041+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'manual_full_load', 'load_dim_store', 'manual__2025-09-20T09:48:23.778100+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/manual_full_load.py', '--cfg-path', '/tmp/tmpmnxn12nr']
[2025-09-20T11:58:31.042+0200] {standard_task_runner.py:85} INFO - Job 65: Subtask load_dim_store
[2025-09-20T11:58:31.087+0200] {task_command.py:410} INFO - Running <TaskInstance: manual_full_load.load_dim_store manual__2025-09-20T09:48:23.778100+00:00 [running]> on host 1102361e702e
[2025-09-20T11:58:31.165+0200] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='manual_full_load' AIRFLOW_CTX_TASK_ID='load_dim_store' AIRFLOW_CTX_EXECUTION_DATE='2025-09-20T09:48:23.778100+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-20T09:48:23.778100+00:00'
[2025-09-20T11:58:31.166+0200] {sql.py:265} INFO - Executing: 
        INSERT INTO dwh.dim_store (store_id, store_name, region)
        SELECT DISTINCT store_id, 'Unknown', 'Unknown'
        FROM staging.sales_stg
        ON CONFLICT (store_id) DO NOTHING;
        
[2025-09-20T11:58:31.180+0200] {base.py:73} INFO - Using connection ID 'postgres_retail' for task execution.
[2025-09-20T11:58:31.228+0200] {base.py:73} INFO - Using connection ID 'postgres_retail' for task execution.
[2025-09-20T11:58:31.233+0200] {sql.py:375} INFO - Running statement: 
        INSERT INTO dwh.dim_store (store_id, store_name, region)
        SELECT DISTINCT store_id, 'Unknown', 'Unknown'
        FROM staging.sales_stg
        ON CONFLICT (store_id) DO NOTHING;
        , parameters: None
[2025-09-20T11:58:31.235+0200] {sql.py:384} INFO - Rows affected: 5
[2025-09-20T11:58:31.245+0200] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=manual_full_load, task_id=load_dim_store, execution_date=20250920T094823, start_date=20250920T095831, end_date=20250920T095831
[2025-09-20T11:58:31.259+0200] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-09-20T11:58:31.304+0200] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
