[2025-09-20T12:04:05.014+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: manual_full_load.load_fct_promotions manual__2025-09-20T09:58:58.018672+00:00 [queued]>
[2025-09-20T12:04:05.022+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: manual_full_load.load_fct_promotions manual__2025-09-20T09:58:58.018672+00:00 [queued]>
[2025-09-20T12:04:05.022+0200] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2025-09-20T12:04:05.033+0200] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): load_fct_promotions> on 2025-09-20 09:58:58.018672+00:00
[2025-09-20T12:04:05.035+0200] {standard_task_runner.py:57} INFO - Started process 7348 to run task
[2025-09-20T12:04:05.038+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'manual_full_load', 'load_fct_promotions', 'manual__2025-09-20T09:58:58.018672+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/manual_full_load.py', '--cfg-path', '/tmp/tmpx9g0b1nx']
[2025-09-20T12:04:05.040+0200] {standard_task_runner.py:85} INFO - Job 104: Subtask load_fct_promotions
[2025-09-20T12:04:05.088+0200] {task_command.py:410} INFO - Running <TaskInstance: manual_full_load.load_fct_promotions manual__2025-09-20T09:58:58.018672+00:00 [running]> on host 1102361e702e
[2025-09-20T12:04:05.169+0200] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='manual_full_load' AIRFLOW_CTX_TASK_ID='load_fct_promotions' AIRFLOW_CTX_EXECUTION_DATE='2025-09-20T09:58:58.018672+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-20T09:58:58.018672+00:00'
[2025-09-20T12:04:05.170+0200] {sql.py:265} INFO - Executing: 
        INSERT INTO dwh.fct_promotions (promo_id, product_id, start_date, end_date, discount, description)
        SELECT promo_id, product_id, start_date, end_date, discount, description
        FROM staging.promotions_stg;
        
[2025-09-20T12:04:05.185+0200] {base.py:73} INFO - Using connection ID 'postgres_retail' for task execution.
[2025-09-20T12:04:05.232+0200] {base.py:73} INFO - Using connection ID 'postgres_retail' for task execution.
[2025-09-20T12:04:05.237+0200] {sql.py:375} INFO - Running statement: 
        INSERT INTO dwh.fct_promotions (promo_id, product_id, start_date, end_date, discount, description)
        SELECT promo_id, product_id, start_date, end_date, discount, description
        FROM staging.promotions_stg;
        , parameters: None
[2025-09-20T12:04:05.239+0200] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "fct_promotions_pkey"
DETAIL:  Key (promo_id)=(1) already exists.

[2025-09-20T12:04:05.248+0200] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=manual_full_load, task_id=load_fct_promotions, execution_date=20250920T095858, start_date=20250920T100405, end_date=20250920T100405
[2025-09-20T12:04:05.259+0200] {standard_task_runner.py:109} ERROR - Failed to execute job 104 for task load_fct_promotions (duplicate key value violates unique constraint "fct_promotions_pkey"
DETAIL:  Key (promo_id)=(1) already exists.
; 7348)
[2025-09-20T12:04:05.304+0200] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-09-20T12:04:05.354+0200] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
